import { PrismaClient } from "@prisma/client";

export async function seedSubjects(prisma: PrismaClient) {

    const predefinedSubjects = [
        // ─── High School ──────────────────────────────────────────────────────────
        // Core
        { name: 'English 1', code: 'ENG1' },
        { name: 'English 2', code: 'ENG2' },
        { name: 'English 3', code: 'ENG3' },
        { name: 'English 4', code: 'ENG4' },
        { name: 'Filipino 1', code: 'FIL1' },
        { name: 'Filipino 2', code: 'FIL2' },
        { name: 'Filipino 3', code: 'FIL3' },
        { name: 'Filipino 4', code: 'FIL4' },
        { name: 'Mathematics 1 (Algebra)', code: 'MATH1' },
        { name: 'Mathematics 2 (Geometry)', code: 'MATH2' },
        { name: 'Mathematics 3 (Statistics)', code: 'MATH3' },
        { name: 'Mathematics 4 (Pre-Calculus)', code: 'MATH4' },
        { name: 'Science 1 (Earth Science)', code: 'SCI1' },
        { name: 'Science 2 (Biology)', code: 'SCI2' },
        { name: 'Science 3 (Chemistry)', code: 'SCI3' },
        { name: 'Science 4 (Physics)', code: 'SCI4' },
        { name: 'Araling Panlipunan 1', code: 'AP1' },
        { name: 'Araling Panlipunan 2', code: 'AP2' },
        { name: 'Araling Panlipunan 3', code: 'AP3' },
        { name: 'Araling Panlipunan 4', code: 'AP4' },
        { name: 'Technology and Livelihood Education', code: 'TLE' },
        { name: 'MAPEH 1', code: 'MAPEH1' },
        { name: 'MAPEH 2', code: 'MAPEH2' },
        { name: 'MAPEH 3', code: 'MAPEH3' },
        { name: 'MAPEH 4', code: 'MAPEH4' },
        { name: 'Edukasyon sa Pagpapakatao 1', code: 'ESP1' },
        { name: 'Edukasyon sa Pagpapakatao 2', code: 'ESP2' },
        { name: 'Edukasyon sa Pagpapakatao 3', code: 'ESP3' },
        { name: 'Edukasyon sa Pagpapakatao 4', code: 'ESP4' },
        // Senior High School - ABM
        { name: 'Business Mathematics', code: 'ABM-BMATH' },
        { name: 'Business Finance', code: 'ABM-BF' },
        { name: 'Fundamentals of Accounting', code: 'ABM-FACCTG' },
        { name: 'Organization and Management', code: 'ABM-OM' },
        { name: 'Applied Economics', code: 'ABM-AECON' },
        // Senior High School - STEM
        { name: 'Pre-Calculus', code: 'STEM-PCAL' },
        { name: 'Basic Calculus', code: 'STEM-BCAL' },
        { name: 'General Chemistry 1', code: 'STEM-GCHEM1' },
        { name: 'General Chemistry 2', code: 'STEM-GCHEM2' },
        { name: 'General Biology 1', code: 'STEM-GBIO1' },
        { name: 'General Biology 2', code: 'STEM-GBIO2' },
        { name: 'General Physics 1', code: 'STEM-GPHY1' },
        { name: 'General Physics 2', code: 'STEM-GPHY2' },
        { name: 'Earth and Life Science', code: 'STEM-ELS' },
        // Senior High School - HUMSS
        { name: 'Creative Writing', code: 'HUMSS-CW' },
        { name: 'Introduction to World Religions', code: 'HUMSS-IWR' },
        { name: 'Philippine Politics and Governance', code: 'HUMSS-PPG' },
        { name: 'Community Engagement', code: 'HUMSS-CE' },
        // Senior High School - TVL
        { name: 'Food and Beverage Services', code: 'TVL-FBS' },
        { name: 'Computer Hardware Servicing', code: 'TVL-CHS' },
        { name: 'Bread and Pastry Production', code: 'TVL-BPP' },

        // ─── College ──────────────────────────────────────────────────────────────
        // General Education
        { name: 'Purposive Communication', code: 'GE-PC' },
        { name: 'Readings in Philippine History', code: 'GE-RPH' },
        { name: 'The Contemporary World', code: 'GE-TCW' },
        { name: 'Mathematics in the Modern World', code: 'GE-MMW' },
        { name: 'Understanding the Self', code: 'GE-UTS' },
        { name: 'Art Appreciation', code: 'GE-ARTAPP' },
        { name: 'Science, Technology and Society', code: 'GE-STS' },
        { name: 'Ethics', code: 'GE-ETHICS' },
        { name: 'The Life and Works of Rizal', code: 'GE-RIZAL' },
        // BSCS / BSIT
        { name: 'Introduction to Computing', code: 'CS-ICOMP' },
        { name: 'Computer Programming 1', code: 'CS-CPROG1' },
        { name: 'Computer Programming 2', code: 'CS-CPROG2' },
        { name: 'Data Structures and Algorithms', code: 'CS-DSA' },
        { name: 'Discrete Mathematics', code: 'CS-DISCMATH' },
        { name: 'Object-Oriented Programming', code: 'CS-OOP' },
        { name: 'Database Management Systems', code: 'CS-DBMS' },
        { name: 'Operating Systems', code: 'CS-OS' },
        { name: 'Computer Networks', code: 'CS-CN' },
        { name: 'Software Engineering', code: 'CS-SE' },
        { name: 'Web Development', code: 'CS-WD' },
        { name: 'Mobile Application Development', code: 'CS-MAD' },
        { name: 'Artificial Intelligence', code: 'CS-AI' },
        { name: 'Capstone Project 1', code: 'CS-CAP1' },
        { name: 'Capstone Project 2', code: 'CS-CAP2' },
        // BSA / BSBA
        { name: 'Financial Accounting 1', code: 'ACCTG1' },
        { name: 'Financial Accounting 2', code: 'ACCTG2' },
        { name: 'Cost Accounting', code: 'ACCTG-COST' },
        { name: 'Management Accounting', code: 'ACCTG-MGT' },
        { name: 'Auditing Theory', code: 'ACCTG-AUD' },
        { name: 'Taxation', code: 'ACCTG-TAX' },
        { name: 'Business Law', code: 'BA-BLAW' },
        { name: 'Principles of Management', code: 'BA-POM' },
        { name: 'Marketing Management', code: 'BA-MM' },
        { name: 'Human Resource Management', code: 'BA-HRM' },
        { name: 'Operations Management', code: 'BA-OM' },
        { name: 'Strategic Management', code: 'BA-SM' },
        // BSEd / BEEd
        { name: 'Child and Adolescent Development', code: 'ED-CAD' },
        { name: 'The Teaching Profession', code: 'ED-TP' },
        { name: 'Curriculum and Instruction', code: 'ED-CI' },
        { name: 'Assessment of Learning 1', code: 'ED-ASMT1' },
        { name: 'Assessment of Learning 2', code: 'ED-ASMT2' },
        { name: 'Facilitating Learner-Centered Teaching', code: 'ED-FLCT' },
        { name: 'Field Study 1', code: 'ED-FS1' },
        { name: 'Field Study 2', code: 'ED-FS2' },
        { name: 'Practice Teaching', code: 'ED-PT' },
        // BSN
        { name: 'Anatomy and Physiology', code: 'NUR-AP' },
        { name: 'Microbiology and Parasitology', code: 'NUR-MP' },
        { name: 'Pharmacology', code: 'NUR-PHARM' },
        { name: 'Medical-Surgical Nursing 1', code: 'NUR-MSN1' },
        { name: 'Medical-Surgical Nursing 2', code: 'NUR-MSN2' },
        { name: 'Maternal and Child Nursing', code: 'NUR-MCN' },
        { name: 'Psychiatric Nursing', code: 'NUR-PSYCH' },
        { name: 'Community Health Nursing', code: 'NUR-CHN' },
    ];

    await prisma.subject.createMany({
        data: predefinedSubjects,
        skipDuplicates: true,
    });

}